set nocompatible              " be iMproved, required
filetype off                  " required

" Having longer updatetime (default is 4000 ms = 4 s) leads to noticeable
" delays and poor user experience.
set updatetime=300

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

Plugin 'junegunn/fzf.vim'
Plugin 'preservim/nerdtree'
Plugin 'buoto/gotests-vim'
Plugin 'preservim/nerdcommenter'
Plugin 'tpope/vim-fugitive'

Plugin 'dracula/vim', { 'name': 'dracula' }

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

" If installed using git
set rtp+=~/.fzf

set incsearch
set hlsearch
set ignorecase
set smartcase

set relativenumber number

map <c-s-n> :Files<CR>
map <c-s-f> :Rg<CR>
map <c-s-j> :GoTest<CR>
map <c-a-l> :GoFmt<CR>
map <c-a-o> :GoImports<CR>
map <C-b> :GoDef<CR>
map <C-S-F9> :GoBuild<CR>
map <C-F12> :GoDecls<CR>
map <C-F8> :DlvToggleBreakpoint<CR>
map <C-F5> :DlvTest<CR>
nmap <silent>gr <Plug>(coc-references)
nmap <silent>gi <Plug>(coc-implementation)
map <C-n> :NERDTreeToggle<CR>
map <A-1> :NERDTree %<CR>

inoremap <silent><expr> <c-space> coc#refresh()

" Highlight the symbol and its references when holding the cursor.
autocmd CursorHold * silent call CocActionAsync('highlight')

colorscheme dracula

" Specify a directory for plugins
" - For Neovim: stdpath('data') . '/plugged'
" - Avoid using standard Vim directory names like 'plugin'
call plug#begin('~/.vim/plugged')

" Make sure you use single quotes

Plug 'sebdah/vim-delve'
Plug 'neoclide/coc.nvim', {'do': 'yarn install --frozen-lockfile'}


" Initialize plugin system
call plug#end()
